name: Deploy PWA to pilot

on:
  push:
    branches: [ main ]

env:
  PRJ: duplo

jobs:
  test_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check-out repo under '$GITHUB_WORKSPACE'.
        uses: actions/checkout@v2

      #      - name: Build application on '$GITHUB_WORKSPACE'.
      #        run: |
      #          npm install

      - name: Copy files to Remote Server.
        uses: easingthemes/ssh-deploy@v2.0.7
        env:
          REMOTE_HOST: ${{ secrets.REMOTE_HOST_CONTABO }}
          REMOTE_USER: ${{ secrets.REMOTE_USER_CONTABO }}
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY_CONTABO }}
          ARGS: "-rltgoDzvO"
          SOURCE: "/"
          TARGET: "/home/github/${{env.PRJ}}.new/"

      - name: Replace old backend files with new ones on Remote Server.
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST_CONTABO }}
          username: ${{ secrets.REMOTE_USER_CONTABO }}
          key: ${{ secrets.SERVER_SSH_KEY_CONTABO }}
          script: |
            cd /home/github/${{env.PRJ}}.new/
            cp ~/cfg/${{env.PRJ}}.local.crypto.keys.json ./cfg/local.crypto.keys.json
            cp ~/cfg/${{env.PRJ}}.local.json ./cfg/local.json
            cp ~/cfg/${{env.PRJ}}.local.vapid.key.json ./cfg/local.vapid.key.json
            /bin/bash ./bin/deploy/dev.sh
            cd /home/github/${{env.PRJ}}/
            npm stop
            cd /home/github/
            rm -fr ./${{env.PRJ}}
            mv ./${{env.PRJ}}.new ./${{env.PRJ}}
            cd ./${{env.PRJ}}/
            nohup npm start > ./output.log 2>&1 &
